apiVersion: apps/v1
kind: Deployment
metadata:
  name: food-delivery-backend
spec:
  selector:
    matchLabels:
      app: food-delivery-backend
  template:
    metadata:
      labels:
        app: food-delivery-backend
    spec:
      containers:
      - name: food-delivery-backend
        image: 40781998/food-delivery-system-backend:latest
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 8000
